---
- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  pre_tasks:
    - name: Debug | var ansible_facts['virtualization_type']
      ansible.builtin.debug:
        var: ansible_facts['virtualization_type']
    - name: Debian os_family
      when:
        - ansible_facts.os_family == 'Debian'
      block:
        - name: Debian | Refresh apt cache
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600
        - name: Ensure sshd is present
          ansible.builtin.package:
            name: openssh-server
            state: present
        - name: Ensure /run/sshd exists
          ansible.builtin.file:
            path: /run/sshd
            state: directory
            mode: "0755"
        - name: Ensure iptables is present
          ansible.builtin.package:
            name: iptables
            state: present
  roles:
    - juju4.harden_nanokvm
